### ISSUE TITLE
computeOpticalFlow.m

### ISSUE THREAD

**Issue by jjy201314** [shuangjiexu/Spatial-Temporal-Pooling-Networks-ReID#5]
i can't creat the  optical flow files. I  ran the computeOpticalFlow.m ,but it didn't work,what can i do ?

**Comment by Redoblue** [comment]
The ".m" code is out dated, your need to use a lower version of matlab.

**Comment by jjy201314** [comment]
i used matlab r2014a, it could run well, but can't creat the   optical flow files,which matlab should i use? @shuangjiexu
